-   id: blackbook
    name: blackbook
    description: "`Black` for Jupyter notebooks."
    entry: blackbook .
    language: python
    language_version: python3
    require_serial: true
    files: '.*\.ipynb'
    exclude: '.*\ipynb_checkpoints'
