name: CI/CD

on:
  push:
  pull_request:
  # Run daily at 0:01 UTC
  schedule:
  - cron:  '1 0 * * *'

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1.1.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -q --no-cache-dir -e .
        python -m pip install -q --no-cache-dir "mypy==0.750" pytest pytest-cov isort coveralls
        python -m pip list
    - name: Lint with mypy
      if: matrix.python-version == 3.7 && matrix.os == 'ubuntu-latest'
      run: |
        mypy src --ignore-missing-imports
    - name: Lint with Black
      if: matrix.python-version == 3.7 && matrix.os == 'ubuntu-latest'
      run: |
        black --check --diff --verbose .
    - name: Lint imports with isort
      if: matrix.python-version == 3.7 && matrix.os == 'ubuntu-latest'
      run: |
        isort -rc . --check-only
    - name: Test with pytest
      run: |
        python -m pytest -s
    - name: Lint with blackbook
      # Needs to go last, else pytest will fail
      if: matrix.python-version == 3.7 && matrix.os == 'ubuntu-latest'
      run: |
        blackbook .
